### PR TITLE
changing in the login css file

### PR DESCRIPTION
**Pull request by ansiace**
## Changes Implemented

1. **Footer Section Improvement:**
   - **Issue Raised:** Added `margin-bottom` to the footer section for better spacing and layout consistency. This resolves spacing issues at the bottom of the page, providing a cleaner and more visually appealing design.

2. **Centered Top Image (Non-Issued Change):**
   - Centered the top image to enhance the overall balance of the page's visual layout. While there was no issue assigned for this change, it contributes to a more symmetrical and professional look for the page.

## Purpose

The changes aim to:
- Improve the page's **visual balance** and **layout consistency**.
- Ensure better **spacing in the footer** for a more polished appearance.
- Center the top image for a more **aesthetically pleasing** user experience.

## Additional Notes

While the top image centering wasn’t part of an assigned issue, I noticed the improvement opportunity and implemented it as part of this PR. Please review and let me know if you'd prefer it to be split into a separate issue or PR.

image

### CODE REVIEW

**Comment by ansiace** [comment]
- closes #94

**Review by hamzathul — APPROVED** [review]

**Comment by ansiace** [comment]
Hi, I hope you're doing well! I noticed that I’ve created a pull request, but it hasn't been merged yet.

**Comment by ansiace** [comment]
@GVishnudhasan you good bro?

**Comment by ansiace** [comment]
Thank you for the suggestion! I'll go ahead and delete the fork if it's no longer needed. Appreciate the heads-up

**Pull request merged**
