### PR TITLE
added notification feature and search bar

### PR DESCRIPTION
**Pull request by GauriSachan**
#45

### CODE REVIEW

**Comment by GauriSachan** [comment]
> #45

please add labels of appropriate level , hacktoberfest and gssoc-ext

**Comment by GVishnudhasan** [comment]
@GauriSachan Kindly drop a video recording of the newly added feature with responsive screen.

**Comment by GauriSachan** [comment]
image

**Comment by GVishnudhasan** [comment]
@GauriSachan Sorry to bother you. Video recording please!

**Comment by GauriSachan** [comment]
> @GauriSachan Sorry to bother you. Video recording please!

@GVishnudhasan hey sorry for the inconvenience but right now my laptop is having a glitch that it is not showing the projects I am working on when I try to open them in browser

**Pull request merged**
